server:
  port: 8080

spring:
    application:
        name: esop
    datasource:
        url: jdbc:mariadb://localhost:3307/esop # in this pc, mariadb is running on port 3307, MySQL is running on port 3306
        username: root
        password: cdcdcd001!
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format-sql: true
                use-sql-comments: true
                jdbc:
                    time-zone: UTC
    output:
        ansi:
            enabled: always

    thymeleaf:
        cache: false  # Disable cache for development, it means that the templates will be reloaded every time they are changed

logging:
  level:
    com:
        soro:
            esop: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(%logger{36}){cyan} - %msg%n"
