server:
  port: 8080

spring:
    application:
        name: esop
    profiles:
        active: mysql # mysql, mariadb
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            javax.persistence.validation.mode: none # disable bean validation for Entity Event Listener working(2024.09.18)
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
                jdbc:
                    time_zone: UTC
    output:
        ansi:
            enabled: always

    thymeleaf:
        cache: false  # Disable cache for development, it means that the templates will be reloaded every time they are changed

    messages:
        basename: i18n/messages

jwt:
  issuer: SORO_LLC
  secret: LBjdLr3e1PeayiSVphUKpLyJR4N7U2cd347MfUCBfyA # used by token provider
  audience: CUSTOMER_SORO_SERVICE
  authorities: authorities
  expiration: 1_800_000 # 30 mins
  refreshExpire: 432_000_000 # 5 days in milliseconds

logging:
  level:
    com:
        soro:
            esop: debug
    org:
        hibernate:
            SQL: DEBUG
            type:
                descriptor:
                    sql:
                        BasicBinder: TRACE
            tool:
                hbm2ddl: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(%logger{36}){cyan} %clr(:%line){magenta} - %msg%n"